services:
  - type: web
    name: ESP32_MAKE
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 1 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iot-command-db
          property: connectionString

databases:
  - name: iot-command-db
    plan: free
    
